// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateChapterTranslationChapterTranslationsPostData, CreateChapterTranslationChapterTranslationsPostErrors, CreateChapterTranslationChapterTranslationsPostResponses, GetChapterForWorkWorksWorkIdChaptersChapterIdGetData, GetChapterForWorkWorksWorkIdChaptersChapterIdGetErrors, GetChapterForWorkWorksWorkIdChaptersChapterIdGetResponses, GetChapterTranslationChapterTranslationsCtIdGetData, GetChapterTranslationChapterTranslationsCtIdGetErrors, GetChapterTranslationChapterTranslationsCtIdGetResponses, GetWorkWorksWorkIdGetData, GetWorkWorksWorkIdGetErrors, GetWorkWorksWorkIdGetResponses, HealthHealthGetData, HealthHealthGetResponses, ImportWorkWorksImportPostData, ImportWorkWorksImportPostErrors, ImportWorkWorksImportPostResponses, IngestSyosetuIngestSyosetuPostData, IngestSyosetuIngestSyosetuPostErrors, IngestSyosetuIngestSyosetuPostResponses, ListChaptersForWorkWorksWorkIdChaptersGetData, ListChaptersForWorkWorksWorkIdChaptersGetErrors, ListChaptersForWorkWorksWorkIdChaptersGetResponses, ListTranslationSegmentsChapterTranslationsCtIdSegmentsGetData, ListTranslationSegmentsChapterTranslationsCtIdSegmentsGetErrors, ListTranslationSegmentsChapterTranslationsCtIdSegmentsGetResponses, RequestChapterScrapeWorksWorkIdScrapeChaptersPostData, RequestChapterScrapeWorksWorkIdScrapeChaptersPostErrors, RequestChapterScrapeWorksWorkIdScrapeChaptersPostResponses, SearchWorksWorksGetData, SearchWorksWorksGetErrors, SearchWorksWorksGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class Default {
    /**
     * Health
     */
    public static healthHealthGet<ThrowOnError extends boolean = false>(options?: Options<HealthHealthGetData, ThrowOnError>) {
        return (options?.client ?? client).get<HealthHealthGetResponses, unknown, ThrowOnError>({
            responseType: 'json',
            url: '/health',
            ...options
        });
    }
}

export class Ingest {
    /**
     * Ingest Syosetu
     */
    public static ingestSyosetuIngestSyosetuPost<ThrowOnError extends boolean = false>(options: Options<IngestSyosetuIngestSyosetuPostData, ThrowOnError>) {
        return (options.client ?? client).post<IngestSyosetuIngestSyosetuPostResponses, IngestSyosetuIngestSyosetuPostErrors, ThrowOnError>({
            responseType: 'json',
            url: '/ingest/syosetu',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class ChapterTranslations {
    /**
     * Create Chapter Translation
     */
    public static createChapterTranslationChapterTranslationsPost<ThrowOnError extends boolean = false>(options: Options<CreateChapterTranslationChapterTranslationsPostData, ThrowOnError>) {
        return (options.client ?? client).post<CreateChapterTranslationChapterTranslationsPostResponses, CreateChapterTranslationChapterTranslationsPostErrors, ThrowOnError>({
            responseType: 'json',
            url: '/chapter-translations/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Get Chapter Translation
     */
    public static getChapterTranslationChapterTranslationsCtIdGet<ThrowOnError extends boolean = false>(options: Options<GetChapterTranslationChapterTranslationsCtIdGetData, ThrowOnError>) {
        return (options.client ?? client).get<GetChapterTranslationChapterTranslationsCtIdGetResponses, GetChapterTranslationChapterTranslationsCtIdGetErrors, ThrowOnError>({
            responseType: 'json',
            url: '/chapter-translations/{ct_id}',
            ...options
        });
    }
    
    /**
     * List Translation Segments
     */
    public static listTranslationSegmentsChapterTranslationsCtIdSegmentsGet<ThrowOnError extends boolean = false>(options: Options<ListTranslationSegmentsChapterTranslationsCtIdSegmentsGetData, ThrowOnError>) {
        return (options.client ?? client).get<ListTranslationSegmentsChapterTranslationsCtIdSegmentsGetResponses, ListTranslationSegmentsChapterTranslationsCtIdSegmentsGetErrors, ThrowOnError>({
            responseType: 'json',
            url: '/chapter-translations/{ct_id}/segments',
            ...options
        });
    }
}

export class Works {
    /**
     * Search Works
     */
    public static searchWorksWorksGet<ThrowOnError extends boolean = false>(options?: Options<SearchWorksWorksGetData, ThrowOnError>) {
        return (options?.client ?? client).get<SearchWorksWorksGetResponses, SearchWorksWorksGetErrors, ThrowOnError>({
            responseType: 'json',
            url: '/works/',
            ...options
        });
    }
    
    /**
     * Import Work
     */
    public static importWorkWorksImportPost<ThrowOnError extends boolean = false>(options: Options<ImportWorkWorksImportPostData, ThrowOnError>) {
        return (options.client ?? client).post<ImportWorkWorksImportPostResponses, ImportWorkWorksImportPostErrors, ThrowOnError>({
            responseType: 'json',
            url: '/works/import',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Get Work
     */
    public static getWorkWorksWorkIdGet<ThrowOnError extends boolean = false>(options: Options<GetWorkWorksWorkIdGetData, ThrowOnError>) {
        return (options.client ?? client).get<GetWorkWorksWorkIdGetResponses, GetWorkWorksWorkIdGetErrors, ThrowOnError>({
            responseType: 'json',
            url: '/works/{work_id}',
            ...options
        });
    }
    
    /**
     * List Chapters For Work
     */
    public static listChaptersForWorkWorksWorkIdChaptersGet<ThrowOnError extends boolean = false>(options: Options<ListChaptersForWorkWorksWorkIdChaptersGetData, ThrowOnError>) {
        return (options.client ?? client).get<ListChaptersForWorkWorksWorkIdChaptersGetResponses, ListChaptersForWorkWorksWorkIdChaptersGetErrors, ThrowOnError>({
            responseType: 'json',
            url: '/works/{work_id}/chapters',
            ...options
        });
    }
    
    /**
     * Get Chapter For Work
     */
    public static getChapterForWorkWorksWorkIdChaptersChapterIdGet<ThrowOnError extends boolean = false>(options: Options<GetChapterForWorkWorksWorkIdChaptersChapterIdGetData, ThrowOnError>) {
        return (options.client ?? client).get<GetChapterForWorkWorksWorkIdChaptersChapterIdGetResponses, GetChapterForWorkWorksWorkIdChaptersChapterIdGetErrors, ThrowOnError>({
            responseType: 'json',
            url: '/works/{work_id}/chapters/{chapter_id}',
            ...options
        });
    }
    
    /**
     * Request Chapter Scrape
     */
    public static requestChapterScrapeWorksWorkIdScrapeChaptersPost<ThrowOnError extends boolean = false>(options: Options<RequestChapterScrapeWorksWorkIdScrapeChaptersPostData, ThrowOnError>) {
        return (options.client ?? client).post<RequestChapterScrapeWorksWorkIdScrapeChaptersPostResponses, RequestChapterScrapeWorksWorkIdScrapeChaptersPostErrors, ThrowOnError>({
            responseType: 'json',
            url: '/works/{work_id}/scrape-chapters',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
