// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * ChapterDetailOut
 */
export type ChapterDetailOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Work Id
     */
    work_id: number;
    /**
     * Idx
     */
    idx: number;
    /**
     * Sort Key
     */
    sort_key: number;
    /**
     * Title
     */
    title: string;
    /**
     * Normalized Text
     */
    normalized_text: string;
};

/**
 * ChapterOut
 */
export type ChapterOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Work Id
     */
    work_id: number;
    /**
     * Idx
     */
    idx: number;
    /**
     * Sort Key
     */
    sort_key: number;
    /**
     * Title
     */
    title: string;
};

/**
 * ChapterPromptOverrideRequest
 */
export type ChapterPromptOverrideRequest = {
    /**
     * Model
     *
     * Model identifier
     */
    model: string;
    /**
     * Template
     *
     * Prompt template to use for this run
     */
    template: string;
    /**
     * Parameters
     *
     * Optional structured parameter overrides
     */
    parameters?: {
        [key: string]: unknown;
    } | null;
};

/**
 * ChapterPromptOverrideResponse
 */
export type ChapterPromptOverrideResponse = {
    /**
     * Token
     */
    token: string;
    /**
     * Expires At
     */
    expires_at: string;
};

/**
 * ChapterScrapeErrorItem
 */
export type ChapterScrapeErrorItem = {
    /**
     * Chapter
     */
    chapter: number;
    /**
     * Reason
     */
    reason: string;
};

/**
 * ChapterScrapeRequest
 */
export type ChapterScrapeRequest = {
    /**
     * Start
     *
     * Starting chapter number (supports decimals)
     */
    start: number;
    /**
     * End
     *
     * Ending chapter number (supports decimals)
     */
    end: number;
    /**
     * Force
     *
     * If true, rescrape existing chapters
     */
    force?: boolean;
};

/**
 * ChapterScrapeResponse
 */
export type ChapterScrapeResponse = {
    /**
     * Work Id
     */
    work_id: number;
    /**
     * Start
     */
    start: number;
    /**
     * End
     */
    end: number;
    /**
     * Force
     */
    force: boolean;
    /**
     * Status
     */
    status: string;
    /**
     * Requested
     */
    requested: number;
    /**
     * Created
     */
    created: number;
    /**
     * Updated
     */
    updated: number;
    /**
     * Skipped
     */
    skipped: number;
    /**
     * Errors
     */
    errors?: Array<ChapterScrapeErrorItem>;
};

/**
 * ChapterTranslationCreate
 */
export type ChapterTranslationCreate = {
    /**
     * Chapter Id
     */
    chapter_id: number;
    /**
     * Cache Policy
     */
    cache_policy?: string;
    /**
     * Params
     */
    params?: {
        [key: string]: unknown;
    } | null;
};

/**
 * ChapterTranslationOut
 */
export type ChapterTranslationOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Chapter Id
     */
    chapter_id: number;
    /**
     * Status
     */
    status: string;
};

/**
 * ChapterTranslationStateOut
 */
export type ChapterTranslationStateOut = {
    /**
     * Chapter Translation Id
     */
    chapter_translation_id: number;
    /**
     * Status
     */
    status: string;
    /**
     * Segments
     */
    segments: Array<TranslationSegmentOut>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IngestSyosetuRequest
 */
export type IngestSyosetuRequest = {
    /**
     * Novel Id
     *
     * Syosetu novel identifier (e.g. n4811fg)
     */
    novel_id: string;
    /**
     * Chapter
     *
     * Chapter number (1-indexed) to fetch
     */
    chapter: number;
};

/**
 * ModelInfoOut
 *
 * Information about a supported LLM model.
 */
export type ModelInfoOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Provider
     */
    provider: string;
    /**
     * Max Tokens
     */
    max_tokens: number;
    /**
     * Supports Streaming
     */
    supports_streaming?: boolean;
    /**
     * Cost Per 1M Input
     */
    cost_per_1m_input?: number;
    /**
     * Cost Per 1M Output
     */
    cost_per_1m_output?: number;
};

/**
 * ModelsListOut
 *
 * list of available models.
 */
export type ModelsListOut = {
    /**
     * Items
     */
    items: Array<ModelInfoOut>;
    /**
     * Total
     */
    total: number;
};

/**
 * PaginatedChaptersOut
 */
export type PaginatedChaptersOut = {
    /**
     * Items
     */
    items: Array<ChapterOut>;
    /**
     * Total
     */
    total: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
};

/**
 * PaginatedPromptVersionsOut
 */
export type PaginatedPromptVersionsOut = {
    /**
     * Items
     */
    items: Array<PromptVersionOut>;
    /**
     * Total
     */
    total: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
};

/**
 * PaginatedPromptsOut
 */
export type PaginatedPromptsOut = {
    /**
     * Items
     */
    items: Array<PromptOut>;
    /**
     * Total
     */
    total: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
};

/**
 * PaginatedWorksOut
 */
export type PaginatedWorksOut = {
    /**
     * Items
     */
    items: Array<WorkOut>;
    /**
     * Total
     */
    total: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
};

/**
 * PromptCreateRequest
 */
export type PromptCreateRequest = {
    /**
     * Name
     *
     * Prompt name
     */
    name: string;
    /**
     * Description
     *
     * Optional description
     */
    description?: string | null;
};

/**
 * PromptDetailOut
 *
 * Prompt with latest version info included.
 */
export type PromptDetailOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Owner Work Id
     */
    owner_work_id?: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    latest_version?: PromptVersionOut | null;
};

/**
 * PromptOut
 */
export type PromptOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Owner Work Id
     */
    owner_work_id?: number | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * PromptUpdateRequest
 */
export type PromptUpdateRequest = {
    /**
     * Name
     *
     * New prompt name
     */
    name?: string | null;
    /**
     * Description
     *
     * New description
     */
    description?: string | null;
};

/**
 * PromptVersionCreateRequest
 */
export type PromptVersionCreateRequest = {
    /**
     * Model
     *
     * Model name (e.g., gpt-4)
     */
    model: string;
    /**
     * Template
     *
     * F-string template for the prompt
     */
    template: string;
    /**
     * Parameters
     *
     * Optional metadata parameters
     */
    parameters?: {
        [key: string]: unknown;
    } | null;
    /**
     * Created By
     *
     * Optional creator identifier
     */
    created_by?: string | null;
};

/**
 * PromptVersionOut
 */
export type PromptVersionOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Prompt Id
     */
    prompt_id: number;
    /**
     * Version Number
     */
    version_number: number;
    /**
     * Model
     */
    model: string;
    /**
     * Template
     */
    template: string;
    /**
     * Parameters
     */
    parameters?: {
        [key: string]: unknown;
    } | null;
    /**
     * Created By
     */
    created_by?: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * TranslationSegmentOut
 */
export type TranslationSegmentOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Start
     */
    start: number;
    /**
     * End
     */
    end: number;
    /**
     * Order Index
     */
    order_index: number;
    /**
     * Src
     */
    src: string;
    /**
     * Tgt
     */
    tgt: string;
    /**
     * Flags
     */
    flags?: Array<string>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * WorkImportRequest
 */
export type WorkImportRequest = {
    /**
     * Url
     *
     * URL to the work homepage or chapter
     */
    url: string;
    /**
     * Force
     *
     * Force re-sync even if the work exists
     */
    force?: boolean;
};

/**
 * WorkOut
 */
export type WorkOut = {
    /**
     * Id
     */
    id: number;
    /**
     * Title
     */
    title: string;
    /**
     * Source
     */
    source?: string | null;
    /**
     * Source Id
     */
    source_id?: string | null;
    /**
     * Source Meta
     */
    source_meta?: {
        [key: string]: unknown;
    } | null;
};

/**
 * WorkPromptUpdateRequest
 */
export type WorkPromptUpdateRequest = {
    /**
     * Prompt Id
     *
     * The prompt ID to set as default for the work
     */
    prompt_id: number;
};

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type IngestSyosetuIngestSyosetuPostData = {
    body: IngestSyosetuRequest;
    path?: never;
    query?: never;
    url: '/ingest/syosetu';
};

export type IngestSyosetuIngestSyosetuPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IngestSyosetuIngestSyosetuPostError = IngestSyosetuIngestSyosetuPostErrors[keyof IngestSyosetuIngestSyosetuPostErrors];

export type IngestSyosetuIngestSyosetuPostResponses = {
    /**
     * Successful Response
     */
    200: ChapterOut;
};

export type IngestSyosetuIngestSyosetuPostResponse = IngestSyosetuIngestSyosetuPostResponses[keyof IngestSyosetuIngestSyosetuPostResponses];

export type CreateChapterTranslationChapterTranslationsPostData = {
    body: ChapterTranslationCreate;
    path?: never;
    query?: never;
    url: '/chapter-translations/';
};

export type CreateChapterTranslationChapterTranslationsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateChapterTranslationChapterTranslationsPostError = CreateChapterTranslationChapterTranslationsPostErrors[keyof CreateChapterTranslationChapterTranslationsPostErrors];

export type CreateChapterTranslationChapterTranslationsPostResponses = {
    /**
     * Successful Response
     */
    200: ChapterTranslationOut;
};

export type CreateChapterTranslationChapterTranslationsPostResponse = CreateChapterTranslationChapterTranslationsPostResponses[keyof CreateChapterTranslationChapterTranslationsPostResponses];

export type GetChapterTranslationChapterTranslationsCtIdGetData = {
    body?: never;
    path: {
        /**
         * Ct Id
         */
        ct_id: number;
    };
    query?: never;
    url: '/chapter-translations/{ct_id}';
};

export type GetChapterTranslationChapterTranslationsCtIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetChapterTranslationChapterTranslationsCtIdGetError = GetChapterTranslationChapterTranslationsCtIdGetErrors[keyof GetChapterTranslationChapterTranslationsCtIdGetErrors];

export type GetChapterTranslationChapterTranslationsCtIdGetResponses = {
    /**
     * Successful Response
     */
    200: ChapterTranslationOut;
};

export type GetChapterTranslationChapterTranslationsCtIdGetResponse = GetChapterTranslationChapterTranslationsCtIdGetResponses[keyof GetChapterTranslationChapterTranslationsCtIdGetResponses];

export type ListTranslationSegmentsChapterTranslationsCtIdSegmentsGetData = {
    body?: never;
    path: {
        /**
         * Ct Id
         */
        ct_id: number;
    };
    query?: never;
    url: '/chapter-translations/{ct_id}/segments';
};

export type ListTranslationSegmentsChapterTranslationsCtIdSegmentsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListTranslationSegmentsChapterTranslationsCtIdSegmentsGetError = ListTranslationSegmentsChapterTranslationsCtIdSegmentsGetErrors[keyof ListTranslationSegmentsChapterTranslationsCtIdSegmentsGetErrors];

export type ListTranslationSegmentsChapterTranslationsCtIdSegmentsGetResponses = {
    /**
     * Response List Translation Segments Chapter Translations  Ct Id  Segments Get
     *
     * Successful Response
     */
    200: Array<TranslationSegmentOut>;
};

export type ListTranslationSegmentsChapterTranslationsCtIdSegmentsGetResponse = ListTranslationSegmentsChapterTranslationsCtIdSegmentsGetResponses[keyof ListTranslationSegmentsChapterTranslationsCtIdSegmentsGetResponses];

export type ListModelsModelsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/models/';
};

export type ListModelsModelsGetResponses = {
    /**
     * Successful Response
     */
    200: ModelsListOut;
};

export type ListModelsModelsGetResponse = ListModelsModelsGetResponses[keyof ListModelsModelsGetResponses];

export type ListPromptsPromptsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/prompts/';
};

export type ListPromptsPromptsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPromptsPromptsGetError = ListPromptsPromptsGetErrors[keyof ListPromptsPromptsGetErrors];

export type ListPromptsPromptsGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedPromptsOut;
};

export type ListPromptsPromptsGetResponse = ListPromptsPromptsGetResponses[keyof ListPromptsPromptsGetResponses];

export type CreatePromptPromptsPostData = {
    body: PromptCreateRequest;
    path?: never;
    query?: never;
    url: '/prompts/';
};

export type CreatePromptPromptsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePromptPromptsPostError = CreatePromptPromptsPostErrors[keyof CreatePromptPromptsPostErrors];

export type CreatePromptPromptsPostResponses = {
    /**
     * Successful Response
     */
    200: PromptOut;
};

export type CreatePromptPromptsPostResponse = CreatePromptPromptsPostResponses[keyof CreatePromptPromptsPostResponses];

export type DeletePromptPromptsPromptIdDeleteData = {
    body?: never;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: number;
    };
    query?: never;
    url: '/prompts/{prompt_id}';
};

export type DeletePromptPromptsPromptIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePromptPromptsPromptIdDeleteError = DeletePromptPromptsPromptIdDeleteErrors[keyof DeletePromptPromptsPromptIdDeleteErrors];

export type DeletePromptPromptsPromptIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeletePromptPromptsPromptIdDeleteResponse = DeletePromptPromptsPromptIdDeleteResponses[keyof DeletePromptPromptsPromptIdDeleteResponses];

export type GetPromptPromptsPromptIdGetData = {
    body?: never;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: number;
    };
    query?: never;
    url: '/prompts/{prompt_id}';
};

export type GetPromptPromptsPromptIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPromptPromptsPromptIdGetError = GetPromptPromptsPromptIdGetErrors[keyof GetPromptPromptsPromptIdGetErrors];

export type GetPromptPromptsPromptIdGetResponses = {
    /**
     * Successful Response
     */
    200: PromptDetailOut;
};

export type GetPromptPromptsPromptIdGetResponse = GetPromptPromptsPromptIdGetResponses[keyof GetPromptPromptsPromptIdGetResponses];

export type UpdatePromptPromptsPromptIdPatchData = {
    body: PromptUpdateRequest;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: number;
    };
    query?: never;
    url: '/prompts/{prompt_id}';
};

export type UpdatePromptPromptsPromptIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePromptPromptsPromptIdPatchError = UpdatePromptPromptsPromptIdPatchErrors[keyof UpdatePromptPromptsPromptIdPatchErrors];

export type UpdatePromptPromptsPromptIdPatchResponses = {
    /**
     * Successful Response
     */
    200: PromptOut;
};

export type UpdatePromptPromptsPromptIdPatchResponse = UpdatePromptPromptsPromptIdPatchResponses[keyof UpdatePromptPromptsPromptIdPatchResponses];

export type ListPromptVersionsPromptsPromptIdVersionsGetData = {
    body?: never;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: number;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/prompts/{prompt_id}/versions';
};

export type ListPromptVersionsPromptsPromptIdVersionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPromptVersionsPromptsPromptIdVersionsGetError = ListPromptVersionsPromptsPromptIdVersionsGetErrors[keyof ListPromptVersionsPromptsPromptIdVersionsGetErrors];

export type ListPromptVersionsPromptsPromptIdVersionsGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedPromptVersionsOut;
};

export type ListPromptVersionsPromptsPromptIdVersionsGetResponse = ListPromptVersionsPromptsPromptIdVersionsGetResponses[keyof ListPromptVersionsPromptsPromptIdVersionsGetResponses];

export type AppendPromptVersionPromptsPromptIdVersionsPostData = {
    body: PromptVersionCreateRequest;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: number;
    };
    query?: never;
    url: '/prompts/{prompt_id}/versions';
};

export type AppendPromptVersionPromptsPromptIdVersionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AppendPromptVersionPromptsPromptIdVersionsPostError = AppendPromptVersionPromptsPromptIdVersionsPostErrors[keyof AppendPromptVersionPromptsPromptIdVersionsPostErrors];

export type AppendPromptVersionPromptsPromptIdVersionsPostResponses = {
    /**
     * Successful Response
     */
    200: PromptVersionOut;
};

export type AppendPromptVersionPromptsPromptIdVersionsPostResponse = AppendPromptVersionPromptsPromptIdVersionsPostResponses[keyof AppendPromptVersionPromptsPromptIdVersionsPostResponses];

export type GetPromptVersionPromptsPromptIdVersionsVersionIdGetData = {
    body?: never;
    path: {
        /**
         * Prompt Id
         */
        prompt_id: number;
        /**
         * Version Id
         */
        version_id: number;
    };
    query?: never;
    url: '/prompts/{prompt_id}/versions/{version_id}';
};

export type GetPromptVersionPromptsPromptIdVersionsVersionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPromptVersionPromptsPromptIdVersionsVersionIdGetError = GetPromptVersionPromptsPromptIdVersionsVersionIdGetErrors[keyof GetPromptVersionPromptsPromptIdVersionsVersionIdGetErrors];

export type GetPromptVersionPromptsPromptIdVersionsVersionIdGetResponses = {
    /**
     * Successful Response
     */
    200: PromptVersionOut;
};

export type GetPromptVersionPromptsPromptIdVersionsVersionIdGetResponse = GetPromptVersionPromptsPromptIdVersionsVersionIdGetResponses[keyof GetPromptVersionPromptsPromptIdVersionsVersionIdGetResponses];

export type ListWorkPromptsPromptsWorksWorkIdPromptsGetData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: number;
    };
    query?: {
        /**
         * Q
         */
        q?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/prompts/works/{work_id}/prompts';
};

export type ListWorkPromptsPromptsWorksWorkIdPromptsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListWorkPromptsPromptsWorksWorkIdPromptsGetError = ListWorkPromptsPromptsWorksWorkIdPromptsGetErrors[keyof ListWorkPromptsPromptsWorksWorkIdPromptsGetErrors];

export type ListWorkPromptsPromptsWorksWorkIdPromptsGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedPromptsOut;
};

export type ListWorkPromptsPromptsWorksWorkIdPromptsGetResponse = ListWorkPromptsPromptsWorksWorkIdPromptsGetResponses[keyof ListWorkPromptsPromptsWorksWorkIdPromptsGetResponses];

export type GetWorkPromptPromptsWorksWorkIdPromptGetData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: number;
    };
    query?: never;
    url: '/prompts/works/{work_id}/prompt';
};

export type GetWorkPromptPromptsWorksWorkIdPromptGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWorkPromptPromptsWorksWorkIdPromptGetError = GetWorkPromptPromptsWorksWorkIdPromptGetErrors[keyof GetWorkPromptPromptsWorksWorkIdPromptGetErrors];

export type GetWorkPromptPromptsWorksWorkIdPromptGetResponses = {
    /**
     * Successful Response
     */
    200: PromptDetailOut;
};

export type GetWorkPromptPromptsWorksWorkIdPromptGetResponse = GetWorkPromptPromptsWorksWorkIdPromptGetResponses[keyof GetWorkPromptPromptsWorksWorkIdPromptGetResponses];

export type UpdateWorkPromptPromptsWorksWorkIdPromptPatchData = {
    body: WorkPromptUpdateRequest;
    path: {
        /**
         * Work Id
         */
        work_id: number;
    };
    query?: never;
    url: '/prompts/works/{work_id}/prompt';
};

export type UpdateWorkPromptPromptsWorksWorkIdPromptPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateWorkPromptPromptsWorksWorkIdPromptPatchError = UpdateWorkPromptPromptsWorksWorkIdPromptPatchErrors[keyof UpdateWorkPromptPromptsWorksWorkIdPromptPatchErrors];

export type UpdateWorkPromptPromptsWorksWorkIdPromptPatchResponses = {
    /**
     * Successful Response
     */
    200: PromptDetailOut;
};

export type UpdateWorkPromptPromptsWorksWorkIdPromptPatchResponse = UpdateWorkPromptPromptsWorksWorkIdPromptPatchResponses[keyof UpdateWorkPromptPromptsWorksWorkIdPromptPatchResponses];

export type SearchWorksWorksGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/works/';
};

export type SearchWorksWorksGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SearchWorksWorksGetError = SearchWorksWorksGetErrors[keyof SearchWorksWorksGetErrors];

export type SearchWorksWorksGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedWorksOut;
};

export type SearchWorksWorksGetResponse = SearchWorksWorksGetResponses[keyof SearchWorksWorksGetResponses];

export type ImportWorkWorksImportPostData = {
    body: WorkImportRequest;
    path?: never;
    query?: never;
    url: '/works/import';
};

export type ImportWorkWorksImportPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportWorkWorksImportPostError = ImportWorkWorksImportPostErrors[keyof ImportWorkWorksImportPostErrors];

export type ImportWorkWorksImportPostResponses = {
    /**
     * Successful Response
     */
    200: WorkOut;
};

export type ImportWorkWorksImportPostResponse = ImportWorkWorksImportPostResponses[keyof ImportWorkWorksImportPostResponses];

export type GetWorkWorksWorkIdGetData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: number;
    };
    query?: never;
    url: '/works/{work_id}';
};

export type GetWorkWorksWorkIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWorkWorksWorkIdGetError = GetWorkWorksWorkIdGetErrors[keyof GetWorkWorksWorkIdGetErrors];

export type GetWorkWorksWorkIdGetResponses = {
    /**
     * Successful Response
     */
    200: WorkOut;
};

export type GetWorkWorksWorkIdGetResponse = GetWorkWorksWorkIdGetResponses[keyof GetWorkWorksWorkIdGetResponses];

export type ListChaptersForWorkWorksWorkIdChaptersGetData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: number;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/works/{work_id}/chapters';
};

export type ListChaptersForWorkWorksWorkIdChaptersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListChaptersForWorkWorksWorkIdChaptersGetError = ListChaptersForWorkWorksWorkIdChaptersGetErrors[keyof ListChaptersForWorkWorksWorkIdChaptersGetErrors];

export type ListChaptersForWorkWorksWorkIdChaptersGetResponses = {
    /**
     * Successful Response
     */
    200: PaginatedChaptersOut;
};

export type ListChaptersForWorkWorksWorkIdChaptersGetResponse = ListChaptersForWorkWorksWorkIdChaptersGetResponses[keyof ListChaptersForWorkWorksWorkIdChaptersGetResponses];

export type GetChapterForWorkWorksWorkIdChaptersChapterIdGetData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: number;
        /**
         * Chapter Id
         */
        chapter_id: number;
    };
    query?: never;
    url: '/works/{work_id}/chapters/{chapter_id}';
};

export type GetChapterForWorkWorksWorkIdChaptersChapterIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetChapterForWorkWorksWorkIdChaptersChapterIdGetError = GetChapterForWorkWorksWorkIdChaptersChapterIdGetErrors[keyof GetChapterForWorkWorksWorkIdChaptersChapterIdGetErrors];

export type GetChapterForWorkWorksWorkIdChaptersChapterIdGetResponses = {
    /**
     * Successful Response
     */
    200: ChapterDetailOut;
};

export type GetChapterForWorkWorksWorkIdChaptersChapterIdGetResponse = GetChapterForWorkWorksWorkIdChaptersChapterIdGetResponses[keyof GetChapterForWorkWorksWorkIdChaptersChapterIdGetResponses];

export type RequestChapterScrapeWorksWorkIdScrapeChaptersPostData = {
    body: ChapterScrapeRequest;
    path: {
        /**
         * Work Id
         */
        work_id: number;
    };
    query?: never;
    url: '/works/{work_id}/scrape-chapters';
};

export type RequestChapterScrapeWorksWorkIdScrapeChaptersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RequestChapterScrapeWorksWorkIdScrapeChaptersPostError = RequestChapterScrapeWorksWorkIdScrapeChaptersPostErrors[keyof RequestChapterScrapeWorksWorkIdScrapeChaptersPostErrors];

export type RequestChapterScrapeWorksWorkIdScrapeChaptersPostResponses = {
    /**
     * Successful Response
     */
    200: ChapterScrapeResponse;
};

export type RequestChapterScrapeWorksWorkIdScrapeChaptersPostResponse = RequestChapterScrapeWorksWorkIdScrapeChaptersPostResponses[keyof RequestChapterScrapeWorksWorkIdScrapeChaptersPostResponses];

export type ResetChapterTranslationWorksWorkIdChaptersChapterIdTranslationDeleteData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: number;
        /**
         * Chapter Id
         */
        chapter_id: number;
    };
    query?: never;
    url: '/works/{work_id}/chapters/{chapter_id}/translation';
};

export type ResetChapterTranslationWorksWorkIdChaptersChapterIdTranslationDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetChapterTranslationWorksWorkIdChaptersChapterIdTranslationDeleteError = ResetChapterTranslationWorksWorkIdChaptersChapterIdTranslationDeleteErrors[keyof ResetChapterTranslationWorksWorkIdChaptersChapterIdTranslationDeleteErrors];

export type ResetChapterTranslationWorksWorkIdChaptersChapterIdTranslationDeleteResponses = {
    /**
     * Successful Response
     */
    200: ChapterTranslationStateOut;
};

export type ResetChapterTranslationWorksWorkIdChaptersChapterIdTranslationDeleteResponse = ResetChapterTranslationWorksWorkIdChaptersChapterIdTranslationDeleteResponses[keyof ResetChapterTranslationWorksWorkIdChaptersChapterIdTranslationDeleteResponses];

export type GetChapterTranslationStateWorksWorkIdChaptersChapterIdTranslationGetData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: number;
        /**
         * Chapter Id
         */
        chapter_id: number;
    };
    query?: never;
    url: '/works/{work_id}/chapters/{chapter_id}/translation';
};

export type GetChapterTranslationStateWorksWorkIdChaptersChapterIdTranslationGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetChapterTranslationStateWorksWorkIdChaptersChapterIdTranslationGetError = GetChapterTranslationStateWorksWorkIdChaptersChapterIdTranslationGetErrors[keyof GetChapterTranslationStateWorksWorkIdChaptersChapterIdTranslationGetErrors];

export type GetChapterTranslationStateWorksWorkIdChaptersChapterIdTranslationGetResponses = {
    /**
     * Successful Response
     */
    200: ChapterTranslationStateOut;
};

export type GetChapterTranslationStateWorksWorkIdChaptersChapterIdTranslationGetResponse = GetChapterTranslationStateWorksWorkIdChaptersChapterIdTranslationGetResponses[keyof GetChapterTranslationStateWorksWorkIdChaptersChapterIdTranslationGetResponses];

export type RegenerateChapterSegmentsWorksWorkIdChaptersChapterIdRegenerateSegmentsPostData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: number;
        /**
         * Chapter Id
         */
        chapter_id: number;
    };
    query?: never;
    url: '/works/{work_id}/chapters/{chapter_id}/regenerate-segments';
};

export type RegenerateChapterSegmentsWorksWorkIdChaptersChapterIdRegenerateSegmentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegenerateChapterSegmentsWorksWorkIdChaptersChapterIdRegenerateSegmentsPostError = RegenerateChapterSegmentsWorksWorkIdChaptersChapterIdRegenerateSegmentsPostErrors[keyof RegenerateChapterSegmentsWorksWorkIdChaptersChapterIdRegenerateSegmentsPostErrors];

export type RegenerateChapterSegmentsWorksWorkIdChaptersChapterIdRegenerateSegmentsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateChapterPromptOverrideWorksWorkIdChaptersChapterIdPromptOverridesPostData = {
    body: ChapterPromptOverrideRequest;
    path: {
        /**
         * Work Id
         */
        work_id: number;
        /**
         * Chapter Id
         */
        chapter_id: number;
    };
    query?: never;
    url: '/works/{work_id}/chapters/{chapter_id}/prompt-overrides';
};

export type CreateChapterPromptOverrideWorksWorkIdChaptersChapterIdPromptOverridesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateChapterPromptOverrideWorksWorkIdChaptersChapterIdPromptOverridesPostError = CreateChapterPromptOverrideWorksWorkIdChaptersChapterIdPromptOverridesPostErrors[keyof CreateChapterPromptOverrideWorksWorkIdChaptersChapterIdPromptOverridesPostErrors];

export type CreateChapterPromptOverrideWorksWorkIdChaptersChapterIdPromptOverridesPostResponses = {
    /**
     * Successful Response
     */
    200: ChapterPromptOverrideResponse;
};

export type CreateChapterPromptOverrideWorksWorkIdChaptersChapterIdPromptOverridesPostResponse = CreateChapterPromptOverrideWorksWorkIdChaptersChapterIdPromptOverridesPostResponses[keyof CreateChapterPromptOverrideWorksWorkIdChaptersChapterIdPromptOverridesPostResponses];

export type StreamChapterTranslationWorksWorkIdChaptersChapterIdTranslateStreamGetData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: number;
        /**
         * Chapter Id
         */
        chapter_id: number;
    };
    query?: {
        /**
         * Prompt Override Token
         */
        prompt_override_token?: string | null;
    };
    url: '/works/{work_id}/chapters/{chapter_id}/translate/stream';
};

export type StreamChapterTranslationWorksWorkIdChaptersChapterIdTranslateStreamGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamChapterTranslationWorksWorkIdChaptersChapterIdTranslateStreamGetError = StreamChapterTranslationWorksWorkIdChaptersChapterIdTranslateStreamGetErrors[keyof StreamChapterTranslationWorksWorkIdChaptersChapterIdTranslateStreamGetErrors];

export type StreamChapterTranslationWorksWorkIdChaptersChapterIdTranslateStreamGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RetranslateSegmentWorksWorkIdChaptersChapterIdSegmentsSegmentIdRetranslateStreamGetData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: number;
        /**
         * Chapter Id
         */
        chapter_id: number;
        /**
         * Segment Id
         */
        segment_id: number;
    };
    query?: {
        /**
         * Prompt Override Token
         */
        prompt_override_token?: string | null;
    };
    url: '/works/{work_id}/chapters/{chapter_id}/segments/{segment_id}/retranslate/stream';
};

export type RetranslateSegmentWorksWorkIdChaptersChapterIdSegmentsSegmentIdRetranslateStreamGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RetranslateSegmentWorksWorkIdChaptersChapterIdSegmentsSegmentIdRetranslateStreamGetError = RetranslateSegmentWorksWorkIdChaptersChapterIdSegmentsSegmentIdRetranslateStreamGetErrors[keyof RetranslateSegmentWorksWorkIdChaptersChapterIdSegmentsSegmentIdRetranslateStreamGetErrors];

export type RetranslateSegmentWorksWorkIdChaptersChapterIdSegmentsSegmentIdRetranslateStreamGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ExplainSegmentWorksWorkIdChaptersChapterIdSegmentsSegmentIdExplainStreamGetData = {
    body?: never;
    path: {
        /**
         * Work Id
         */
        work_id: number;
        /**
         * Chapter Id
         */
        chapter_id: number;
        /**
         * Segment Id
         */
        segment_id: number;
    };
    query?: never;
    url: '/works/{work_id}/chapters/{chapter_id}/segments/{segment_id}/explain/stream';
};

export type ExplainSegmentWorksWorkIdChaptersChapterIdSegmentsSegmentIdExplainStreamGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExplainSegmentWorksWorkIdChaptersChapterIdSegmentsSegmentIdExplainStreamGetError = ExplainSegmentWorksWorkIdChaptersChapterIdSegmentsSegmentIdExplainStreamGetErrors[keyof ExplainSegmentWorksWorkIdChaptersChapterIdSegmentsSegmentIdExplainStreamGetErrors];

export type ExplainSegmentWorksWorkIdChaptersChapterIdSegmentsSegmentIdExplainStreamGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
