"""work_prompts

Revision ID: 26a2bf9dc2bf
Revises: 9b336c20d318
Create Date: 2025-11-11 17:16:02.785831
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = "26a2bf9dc2bf"
down_revision = "9b336c20d318"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chapter_translations", sa.Column("model_snapshot", sa.String(length=128), nullable=True)
    )
    op.add_column("chapter_translations", sa.Column("template_snapshot", sa.Text(), nullable=True))
    op.add_column(
        "chapter_translations", sa.Column("parameters_snapshot", sa.JSON(), nullable=True)
    )
    op.create_index(
        op.f("ix_chapter_translations_prompt_version_id"),
        "chapter_translations",
        ["prompt_version_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_chapter_translations_prompt_version_id"), table_name="chapter_translations"
    )
    op.drop_column("chapter_translations", "parameters_snapshot")
    op.drop_column("chapter_translations", "template_snapshot")
    op.drop_column("chapter_translations", "model_snapshot")
    # ### end Alembic commands ###
