"""add_scrape_jobs

Revision ID: 6727872b16b1
Revises: a21635cef4ae
Create Date: 2026-01-16 03:06:13.839360
"""
from __future__ import annotations

revision = "6727872b16b1"
down_revision = 'a21635cef4ae'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_chapter_work_sort_key', 'chapters', ['work_id', 'sort_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_chapter_work_sort_key', 'chapters', type_='unique')
    # ### end Alembic commands ###
