"""scrape_job_error_tracking

Revision ID: 6f045d79ba94
Revises: 78bfe9799614
Create Date: 2026-04-05 03:42:17.821071
"""
from __future__ import annotations

revision = "6f045d79ba94"
down_revision = '78bfe9799614'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrape_jobs', sa.Column('failed_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('scrape_jobs', sa.Column('created_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('scrape_jobs', sa.Column('updated_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('scrape_jobs', sa.Column('skipped_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('scrape_jobs', sa.Column('error_details', sa.JSON(), nullable=True))
    op.alter_column('scrape_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scrape_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scrape_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scrape_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('scrape_jobs', 'error_details')
    op.drop_column('scrape_jobs', 'skipped_count')
    op.drop_column('scrape_jobs', 'updated_count')
    op.drop_column('scrape_jobs', 'created_count')
    op.drop_column('scrape_jobs', 'failed_count')
    # ### end Alembic commands ###
