"""chapter_last_read_at

Revision ID: 77439a9ac036
Revises: af989bf1dba4
Create Date: 2026-05-03 09:19:41.198195
"""
from __future__ import annotations

revision = "77439a9ac036"
down_revision = 'af989bf1dba4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_chapters_last_read_at'), 'chapters', ['last_read_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chapters_last_read_at'), table_name='chapters')
    op.drop_column('chapters', 'last_read_at')
    # ### end Alembic commands ###
