"""chapter_groups

Revision ID: 78bfe9799614
Revises: 6727872b16b1
Create Date: 2026-01-16 09:07:44.296472
"""
from __future__ import annotations

revision = "78bfe9799614"
down_revision = '6727872b16b1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('work_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_id', 'name', name='uq_group_work_name')
    )
    op.create_index(op.f('ix_chapter_groups_work_id'), 'chapter_groups', ['work_id'], unique=False)
    op.create_table('chapter_group_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['chapter_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id', name='uq_chapter_single_group'),
    sa.UniqueConstraint('group_id', 'order_index', name='uq_group_order')
    )
    op.create_index(op.f('ix_chapter_group_members_chapter_id'), 'chapter_group_members', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_chapter_group_members_group_id'), 'chapter_group_members', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chapter_group_members_group_id'), table_name='chapter_group_members')
    op.drop_index(op.f('ix_chapter_group_members_chapter_id'), table_name='chapter_group_members')
    op.drop_table('chapter_group_members')
    op.drop_index(op.f('ix_chapter_groups_work_id'), table_name='chapter_groups')
    op.drop_table('chapter_groups')
    # ### end Alembic commands ###
