"""chapter_source_chapter_id

Revision ID: 8eb2a39579b1
Revises: 77439a9ac036
Create Date: 2026-06-27 16:49:36.140922
"""
from __future__ import annotations

revision = "8eb2a39579b1"
down_revision = '77439a9ac036'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('source_chapter_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'source_chapter_id')
    # ### end Alembic commands ###
