"""explanation

Revision ID: a21635cef4ae
Revises: 10bfc5549ef2
Create Date: 2025-11-15 15:43:33.105766
"""
from __future__ import annotations

revision = "a21635cef4ae"
down_revision = '10bfc5549ef2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chapter_prompt_overrides_chapter_id', table_name='chapter_prompt_overrides')
    op.drop_index('ix_chapter_prompt_overrides_work_id', table_name='chapter_prompt_overrides')
    op.drop_table('chapter_prompt_overrides')
    op.add_column('translation_segments', sa.Column('explanation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translation_segments', 'explanation')
    op.create_table('chapter_prompt_overrides',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('work_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('template', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name='chapter_prompt_overrides_chapter_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], name='chapter_prompt_overrides_work_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='chapter_prompt_overrides_pkey')
    )
    op.create_index('ix_chapter_prompt_overrides_work_id', 'chapter_prompt_overrides', ['work_id'], unique=False)
    op.create_index('ix_chapter_prompt_overrides_chapter_id', 'chapter_prompt_overrides', ['chapter_id'], unique=False)
    # ### end Alembic commands ###
