"""add_work_jlpt_level

Revision ID: af989bf1dba4
Revises: c7b22fe6a81e
Create Date: 2026-04-17 12:03:04.305165
"""
from __future__ import annotations

revision = "af989bf1dba4"
down_revision = 'c7b22fe6a81e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('works', sa.Column('jlpt_level', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'jlpt_level')
    # ### end Alembic commands ###
