"""translation_explanation_tables

Revision ID: c7b22fe6a81e
Revises: 6f045d79ba94
Create Date: 2026-04-12 13:29:11.612104
"""
from __future__ import annotations

revision = "c7b22fe6a81e"
down_revision = '6f045d79ba94'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_explanations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_unit_type', sa.String(length=32), nullable=False),
    sa.Column('anchor_segment_id', sa.Integer(), nullable=False),
    sa.Column('chapter_translation_id', sa.Integer(), nullable=False),
    sa.Column('span_start', sa.Integer(), nullable=True),
    sa.Column('span_end', sa.Integer(), nullable=True),
    sa.Column('density', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('generator_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['anchor_segment_id'], ['translation_segments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chapter_translation_id'], ['chapter_translations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anchor_segment_id', 'span_start', 'span_end', 'density', name='uq_explanation_segment_span_density')
    )
    op.create_index(op.f('ix_translation_explanations_anchor_segment_id'), 'translation_explanations', ['anchor_segment_id'], unique=False)
    op.create_index(op.f('ix_translation_explanations_chapter_translation_id'), 'translation_explanations', ['chapter_translation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translation_explanations_chapter_translation_id'), table_name='translation_explanations')
    op.drop_index(op.f('ix_translation_explanations_anchor_segment_id'), table_name='translation_explanations')
    op.drop_table('translation_explanations')
    # ### end Alembic commands ###
